services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel_data
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: 31183118
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - teste
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lucasgcbennertz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 31183118
    ports:
      - "8081:80"
    networks:
      - teste

volumes:
  db_data:
networks:
  teste: